// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZBAOg05cfda595z4xORpjAYXmkusj1UM',
    appId: '1:633592906834:web:5bec34a08515cf6a96cb8b',
    messagingSenderId: '633592906834',
    projectId: 'flash-chat-15ff6',
    authDomain: 'flash-chat-15ff6.firebaseapp.com',
    storageBucket: 'flash-chat-15ff6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDos-54ztsAqt8kpD8i8_xDqGgchrSBJhs',
    appId: '1:633592906834:android:c5eda278db05cfa396cb8b',
    messagingSenderId: '633592906834',
    projectId: 'flash-chat-15ff6',
    storageBucket: 'flash-chat-15ff6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnHC4g7nd7nzaH1d38CgekK82VCwMWJnQ',
    appId: '1:633592906834:ios:a46a8fd1e31bbd2b96cb8b',
    messagingSenderId: '633592906834',
    projectId: 'flash-chat-15ff6',
    storageBucket: 'flash-chat-15ff6.firebasestorage.app',
    iosBundleId: 'rahulmathur.com.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnHC4g7nd7nzaH1d38CgekK82VCwMWJnQ',
    appId: '1:633592906834:ios:a46a8fd1e31bbd2b96cb8b',
    messagingSenderId: '633592906834',
    projectId: 'flash-chat-15ff6',
    storageBucket: 'flash-chat-15ff6.firebasestorage.app',
    iosBundleId: 'rahulmathur.com.flashChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZBAOg05cfda595z4xORpjAYXmkusj1UM',
    appId: '1:633592906834:web:d21727812b08fd2296cb8b',
    messagingSenderId: '633592906834',
    projectId: 'flash-chat-15ff6',
    authDomain: 'flash-chat-15ff6.firebaseapp.com',
    storageBucket: 'flash-chat-15ff6.firebasestorage.app',
  );

}